export enum CountryCode {
  WW = 'WW',
  AD = 'AD',
  AE = 'AE',
  AF = 'AF',
  AG = 'AG',
  AI = 'AI',
  AL = 'AL',
  AM = 'AM',
  AO = 'AO',
  AR = 'AR',
  AS = 'AS',
  AT = 'AT',
  AU = 'AU',
  AW = 'AW',
  AX = 'AX',
  AZ = 'AZ',

  BA = 'BA',
  BB = 'BB',
  BD = 'BD',
  BE = 'BE',
  BF = 'BF',
  BG = 'BG',
  BH = 'BH',
  BI = 'BI',
  BJ = 'BJ',
  BL = 'BL',
  BM = 'BM',
  BN = 'BN',
  BO = 'BO',
  BQ_1 = 'BQ-1',
  BQ_2 = 'BQ-2',
  BQ = 'BQ',
  BR = 'BR',
  BS = 'BS',
  BT = 'BT',
  BW = 'BW',
  BY = 'BY',
  BZ = 'BZ',

  CA = 'CA',
  CC = 'CC',
  CD_1 = 'CD-1',
  CD = 'CD',
  CF = 'CF',
  CH = 'CH',
  CK = 'CK',
  CL = 'CL',
  CM = 'CM',
  CN = 'CN',
  CO = 'CO',
  CR = 'CR',
  CU = 'CU',
  CW = 'CW',
  CX = 'CX',
  CY = 'CY',
  CZ = 'CZ',

  DE = 'DE',
  DJ = 'DJ',
  DK = 'DK',
  DM = 'DM',
  DO = 'DO',
  DS = 'DS',
  DZ = 'DZ',
  EC = 'EC',
  EE = 'EE',
  EG = 'EG',
  EH = 'EH',
  ER = 'ER',
  ES = 'ES',
  ET = 'ET',
  FI = 'FI',
  FJ = 'FJ',
  FK = 'FK',
  FM = 'FM',
  FO = 'FO',
  FR = 'FR',
  GA = 'GA',
  GB_2 = 'GB-2',
  GB = 'GB',
  GD = 'GD',
  GE = 'GE',
  GG = 'GG',
  GH = 'GH',
  GI = 'GI',
  GL = 'GL',
  GM = 'GM',
  GN = 'GN',
  GQ = 'GQ',
  GR = 'GR',
  GT = 'GT',
  GU = 'GU',
  GW = 'GW',
  GY = 'GY',

  HK = 'HK',
  HN = 'HN',
  HR = 'HR',
  HT = 'HT',
  HU = 'HU',
  ID = 'ID',
  IE = 'IE',
  IL = 'IL',
  IM = 'IM',
  IN = 'IN',
  IO = 'IO',
  IQ = 'IQ',
  IR = 'IR',
  IS = 'IS',
  IT = 'IT',
  JE = 'JE',
  JM = 'JM',
  JO = 'JO',
  JP = 'JP',
  KE = 'KE',
  KG = 'KG',
  KH = 'KH',
  KI = 'KI',
  KM = 'KM',
  KN = 'KN',
  KP = 'KP',
  KR = 'KR',
  KW = 'KW',
  KY = 'KY',
  KZ = 'KZ',
  LA = 'LA',
  LB = 'LB',
  LC = 'LC',
  LI = 'LI',
  LK = 'LK',
  LR = 'LR',
  LS = 'LS',
  LT = 'LT',
  LU = 'LU',
  LV = 'LV',
  LY = 'LY',
  MA = 'MA',
  MC = 'MC',
  MD = 'MD',
  ME = 'ME',
  MG = 'MG',
  MH = 'MH',
  MK = 'MK',
  ML = 'ML',
  MM = 'MM',
  MN = 'MN',
  MO = 'MO',
  MP = 'MP',
  MQ = 'MQ',
  MR = 'MR',
  MS = 'MS',
  MT = 'MT',
  MU = 'MU',
  MV = 'MV',
  MW = 'MW',
  MX = 'MX',
  MY = 'MY',
  MZ = 'MZ',
  NA = 'NA',
  NE = 'NE',
  NF = 'NF',
  NG = 'NG',
  NI = 'NI',
  NL = 'NL',
  NO = 'NO',
  NP = 'NP',
  NR = 'NR',
  NU = 'NU',
  NZ = 'NZ',
  OM = 'OM',
  PA = 'PA',
  PE = 'PE',
  PF = 'PF',
  PG = 'PG',
  PH = 'PH',
  PK = 'PK',
  PL = 'PL',
  PN = 'PN',
  PR = 'PR',
  PS = 'PS',
  PT = 'PT',
  PW = 'PW',
  PY = 'PY',
  QA = 'QA',
  RO = 'RO',
  RS = 'RS',
  RU = 'RU',
  RW = 'RW',
  SA = 'SA',
  SB = 'SB',
  SC = 'SC',
  SE = 'SE',
  SG = 'SG',
  SI = 'SI',
  SK = 'SK',
  SL = 'SL',
  SM = 'SM',
  SN = 'SN',
  SO = 'SO',
  SR = 'SR',
  SS = 'SS',
  ST = 'ST',
  SV = 'SV',
  SX = 'SX',
  SY = 'SY',
  SZ = 'SZ',
  TC = 'TC',
  TD = 'TD',
  TG = 'TG',
  TH = 'TH',
  TJ = 'TJ',
  TK = 'TK',
  TL = 'TL',
  TM = 'TM',
  TN = 'TN',
  TO = 'TO',
  TR = 'TR',
  TT = 'TT',
  TV = 'TV',
  TW = 'TW',
  TZ = 'TZ',
  UA = 'UA',
  UG = 'UG',
  US = 'US',
  UY = 'UY',
  UZ = 'UZ',
  VC = 'VC',
  VE = 'VE',
  VG = 'VG',
  VI = 'VI',
  VN = 'VN',
  VU = 'VU',
  WS = 'WS',
  YE = 'YE',
  ZA = 'ZA',
  ZM = 'ZM',
  ZW = 'ZW',
  AQ = 'AQ', // Antarctica
  BV = 'BV', // Bouvet Island
  CV = 'CV', // Cape Verde
  CG = 'CG', // Congo
  CI = 'CI', // Côte d'Ivoire
  GF = 'GF', // French Guiana
  TF = 'TF', // French Southern Territories
  GP = 'GP', // Guadeloupe
  HM = 'HM', // Heard Island and McDonald Islands
  VA = 'VA', // Holy See
  YT = 'YT', // Mayotte
  AN = 'AN', // Netherlands Antilles
  NC = 'NC', // New Caledonia
  RE = 'RE', // Réunion
  SH = 'SH', // Saint Helena
  PM = 'PM', // Saint Pierre and Miquelon,
  GS = 'GS', // South Georgia and the South Sandwich Islands
  SD = 'SD', // Sudan
  SJ = 'SJ', // Svalbard and Jan Mayen
  UM = 'UM', // United States Minor Outlying Islands
}

export const countryCodeArray: CountryCode[] = [
  CountryCode.AD,
  CountryCode.AE,
  CountryCode.AF,
  CountryCode.AG,
  CountryCode.AI,
  CountryCode.AL,
  CountryCode.AM,
  CountryCode.AO,
  CountryCode.AR,
  CountryCode.AS,
  CountryCode.AT,
  CountryCode.AU,
  CountryCode.AW,
  CountryCode.AX,
  CountryCode.AZ,
  CountryCode.BA,
  CountryCode.BB,
  CountryCode.BD,
  CountryCode.BE,
  CountryCode.BF,
  CountryCode.BG,
  CountryCode.BH,
  CountryCode.BI,
  CountryCode.BJ,
  CountryCode.BL,
  CountryCode.BM,
  CountryCode.BN,
  CountryCode.BO,
  CountryCode.BQ_1,
  CountryCode.BQ_2,
  CountryCode.BQ,
  CountryCode.BR,
  CountryCode.BS,
  CountryCode.BT,
  CountryCode.BW,
  CountryCode.BY,
  CountryCode.BZ,
  CountryCode.CA,
  CountryCode.CC,
  CountryCode.CD_1,
  CountryCode.CD,
  CountryCode.CF,
  CountryCode.CH,
  CountryCode.CK,
  CountryCode.CL,
  CountryCode.CM,
  CountryCode.CN,
  CountryCode.CO,
  CountryCode.CR,
  CountryCode.CU,
  CountryCode.CW,
  CountryCode.CX,
  CountryCode.CY,
  CountryCode.CZ,
  CountryCode.DE,
  CountryCode.DJ,
  CountryCode.DK,
  CountryCode.DM,
  CountryCode.DO,
  CountryCode.DS,
  CountryCode.DZ,
  CountryCode.EC,
  CountryCode.EE,
  CountryCode.EG,
  CountryCode.EH,
  CountryCode.ER,
  CountryCode.ES,
  CountryCode.ET,
  CountryCode.FI,
  CountryCode.FJ,
  CountryCode.FK,
  CountryCode.FM,
  CountryCode.FO,
  CountryCode.FR,
  CountryCode.GA,
  CountryCode.GB_2,
  CountryCode.GB,
  CountryCode.GD,
  CountryCode.GE,
  CountryCode.GG,
  CountryCode.GH,
  CountryCode.GI,
  CountryCode.GL,
  CountryCode.GM,
  CountryCode.GN,
  CountryCode.GQ,
  CountryCode.GR,
  CountryCode.GT,
  CountryCode.GU,
  CountryCode.GW,
  CountryCode.GY,
  CountryCode.HK,
  CountryCode.HN,
  CountryCode.HR,
  CountryCode.HT,
  CountryCode.HU,
  CountryCode.ID,
  CountryCode.IE,
  CountryCode.IL,
  CountryCode.IM,
  CountryCode.IN,
  CountryCode.IO,
  CountryCode.IQ,
  CountryCode.IR,
  CountryCode.IS,
  CountryCode.IT,
  CountryCode.JE,
  CountryCode.JM,
  CountryCode.JO,
  CountryCode.JP,
  CountryCode.KE,
  CountryCode.KG,
  CountryCode.KH,
  CountryCode.KI,
  CountryCode.KM,
  CountryCode.KN,
  CountryCode.KP,
  CountryCode.KR,
  CountryCode.KW,
  CountryCode.KY,
  CountryCode.KZ,
  CountryCode.LA,
  CountryCode.LB,
  CountryCode.LC,
  CountryCode.LI,
  CountryCode.LK,
  CountryCode.LR,
  CountryCode.LS,
  CountryCode.LT,
  CountryCode.LU,
  CountryCode.LV,
  CountryCode.LY,
  CountryCode.MA,
  CountryCode.MC,
  CountryCode.MD,
  CountryCode.ME,
  CountryCode.MG,
  CountryCode.MH,
  CountryCode.MK,
  CountryCode.ML,
  CountryCode.MM,
  CountryCode.MN,
  CountryCode.MO,
  CountryCode.MP,
  CountryCode.MQ,
  CountryCode.MR,
  CountryCode.MS,
  CountryCode.MT,
  CountryCode.MU,
  CountryCode.MV,
  CountryCode.MW,
  CountryCode.MX,
  CountryCode.MY,
  CountryCode.MZ,
  CountryCode.NA,
  CountryCode.NE,
  CountryCode.NF,
  CountryCode.NG,
  CountryCode.NI,
  CountryCode.NL,
  CountryCode.NO,
  CountryCode.NP,
  CountryCode.NR,
  CountryCode.NU,
  CountryCode.NZ,
  CountryCode.OM,
  CountryCode.PA,
  CountryCode.PE,
  CountryCode.PF,
  CountryCode.PG,
  CountryCode.PH,
  CountryCode.PK,
  CountryCode.PL,
  CountryCode.PN,
  CountryCode.PR,
  CountryCode.PS,
  CountryCode.PT,
  CountryCode.PW,
  CountryCode.PY,
  CountryCode.QA,
  CountryCode.RO,
  CountryCode.RS,
  CountryCode.RU,
  CountryCode.RW,
  CountryCode.SA,
  CountryCode.SB,
  CountryCode.SC,
  CountryCode.SE,
  CountryCode.SG,
  CountryCode.SI,
  CountryCode.SK,
  CountryCode.SL,
  CountryCode.SM,
  CountryCode.SN,
  CountryCode.SO,
  CountryCode.SR,
  CountryCode.SS,
  CountryCode.ST,
  CountryCode.SV,
  CountryCode.SX,
  CountryCode.SY,
  CountryCode.SZ,
  CountryCode.TC,
  CountryCode.TD,
  CountryCode.TG,
  CountryCode.TH,
  CountryCode.TJ,
  CountryCode.TK,
  CountryCode.TL,
  CountryCode.TM,
  CountryCode.TN,
  CountryCode.TO,
  CountryCode.TR,
  CountryCode.TT,
  CountryCode.TV,
  CountryCode.TW,
  CountryCode.TZ,
  CountryCode.UA,
  CountryCode.UG,
  CountryCode.US,
  CountryCode.UY,
  CountryCode.UZ,
  CountryCode.VC,
  CountryCode.VE,
  CountryCode.VG,
  CountryCode.VI,
  CountryCode.VN,
  CountryCode.VU,
  CountryCode.WS,
  CountryCode.YE,
  CountryCode.ZA,
  CountryCode.ZM,
  CountryCode.ZW,
  CountryCode.AQ,
  CountryCode.BV,
  CountryCode.CV,
  CountryCode.CG,
  CountryCode.CI,
  CountryCode.GF,
  CountryCode.TF,
  CountryCode.GP,
  CountryCode.HM,
  CountryCode.VA,
  CountryCode.YT,
  CountryCode.AN,
  CountryCode.NC,
  CountryCode.RE,
  CountryCode.SH,
  CountryCode.PM,
  CountryCode.GS,
  CountryCode.SD,
  CountryCode.SJ,
  CountryCode.UM,
];

export const mapCountryCodeToName: { [key in CountryCode]: string } = {
  [CountryCode.WW]: 'country.WW',
  [CountryCode.AD]: 'country.AD',
  [CountryCode.AE]: 'country.AE',
  [CountryCode.AF]: 'country.AF',
  [CountryCode.AG]: 'country.AG',
  [CountryCode.AI]: 'country.AI',
  [CountryCode.AL]: 'country.AL',
  [CountryCode.AM]: 'country.AM',
  [CountryCode.AO]: 'country.AO',
  [CountryCode.AR]: 'country.AR',
  [CountryCode.AS]: 'country.AS',
  [CountryCode.AT]: 'country.AT',
  [CountryCode.AU]: 'country.AU',
  [CountryCode.AW]: 'country.AW',
  [CountryCode.AX]: 'country.AX',
  [CountryCode.AZ]: 'country.AZ',
  [CountryCode.BA]: 'country.BA',
  [CountryCode.BB]: 'country.BB',
  [CountryCode.BD]: 'country.BD',
  [CountryCode.BE]: 'country.BE',
  [CountryCode.BF]: 'country.BF',
  [CountryCode.BG]: 'country.BG',
  [CountryCode.BH]: 'country.BH',
  [CountryCode.BI]: 'country.BI',
  [CountryCode.BJ]: 'country.BJ',
  [CountryCode.BL]: 'country.BL',
  [CountryCode.BM]: 'country.BM',
  [CountryCode.BN]: 'country.BN',
  [CountryCode.BO]: 'country.BO',
  [CountryCode.BQ_1]: 'country.BQ_1',
  [CountryCode.BQ_2]: 'country.BQ_2',
  [CountryCode.BQ]: 'country.BQ',
  [CountryCode.BR]: 'country.BR',
  [CountryCode.BS]: 'country.BS',
  [CountryCode.BT]: 'country.BT',
  [CountryCode.BW]: 'country.BW',
  [CountryCode.BY]: 'country.BY',
  [CountryCode.BZ]: 'country.BZ',
  [CountryCode.CA]: 'country.CA',
  [CountryCode.CC]: 'country.CC',
  [CountryCode.CD_1]: 'country.CD_1',
  [CountryCode.CD]: 'country.CD',
  [CountryCode.CF]: 'country.CF',
  [CountryCode.CH]: 'country.CH',
  [CountryCode.CK]: 'country.CK',
  [CountryCode.CL]: 'country.CL',
  [CountryCode.CM]: 'country.CM',
  [CountryCode.CN]: 'country.CN',
  [CountryCode.CO]: 'country.CO',
  [CountryCode.CR]: 'country.CR',
  [CountryCode.CU]: 'country.CU',
  [CountryCode.CW]: 'country.CW',
  [CountryCode.CX]: 'country.CX',
  [CountryCode.CY]: 'country.CY',
  [CountryCode.CZ]: 'country.CZ',
  [CountryCode.DE]: 'country.DE',
  [CountryCode.DJ]: 'country.DJ',
  [CountryCode.DK]: 'country.DK',
  [CountryCode.DM]: 'country.DM',
  [CountryCode.DO]: 'country.DO',
  [CountryCode.DS]: 'country.DS',
  [CountryCode.DZ]: 'country.DZ',
  [CountryCode.EC]: 'country.EC',
  [CountryCode.EE]: 'country.EE',
  [CountryCode.EG]: 'country.EG',
  [CountryCode.EH]: 'country.EH',
  [CountryCode.ER]: 'country.ER',
  [CountryCode.ES]: 'country.ES',
  [CountryCode.ET]: 'country.ET',
  [CountryCode.FI]: 'country.FI',
  [CountryCode.FJ]: 'country.FJ',
  [CountryCode.FK]: 'country.FK',
  [CountryCode.FM]: 'country.FM',
  [CountryCode.FO]: 'country.FO',
  [CountryCode.FR]: 'country.FR',
  [CountryCode.GA]: 'country.GA',
  [CountryCode.GB_2]: 'country.GB_2',
  [CountryCode.GB]: 'country.GB',
  [CountryCode.GD]: 'country.GD',
  [CountryCode.GE]: 'country.GE',
  [CountryCode.GG]: 'country.GG',
  [CountryCode.GH]: 'country.GH',
  [CountryCode.GI]: 'country.GI',
  [CountryCode.GL]: 'country.GL',
  [CountryCode.GM]: 'country.GM',
  [CountryCode.GN]: 'country.GN',
  [CountryCode.GQ]: 'country.GQ',
  [CountryCode.GR]: 'country.GR',
  [CountryCode.GT]: 'country.GT',
  [CountryCode.GU]: 'country.GU',
  [CountryCode.GW]: 'country.GW',
  [CountryCode.GY]: 'country.GY',
  [CountryCode.HK]: 'country.HK',
  [CountryCode.HN]: 'country.HN',
  [CountryCode.HR]: 'country.HR',
  [CountryCode.HT]: 'country.HT',
  [CountryCode.HU]: 'country.HU',
  [CountryCode.ID]: 'country.ID',
  [CountryCode.IE]: 'country.IE',
  [CountryCode.IL]: 'country.IL',
  [CountryCode.IM]: 'country.IM',
  [CountryCode.IN]: 'country.IN',
  [CountryCode.IO]: 'country.IO',
  [CountryCode.IQ]: 'country.IQ',
  [CountryCode.IR]: 'country.IR',
  [CountryCode.IS]: 'country.IS',
  [CountryCode.IT]: 'country.IT',
  [CountryCode.JE]: 'country.JE',
  [CountryCode.JM]: 'country.JM',
  [CountryCode.JO]: 'country.JO',
  [CountryCode.JP]: 'country.JP',
  [CountryCode.KE]: 'country.KE',
  [CountryCode.KG]: 'country.KG',
  [CountryCode.KH]: 'country.KH',
  [CountryCode.KI]: 'country.KI',
  [CountryCode.KM]: 'country.KM',
  [CountryCode.KN]: 'country.KN',
  [CountryCode.KP]: 'country.KP',
  [CountryCode.KR]: 'country.KR',
  [CountryCode.KW]: 'country.KW',
  [CountryCode.KY]: 'country.KY',
  [CountryCode.KZ]: 'country.KZ',
  [CountryCode.LA]: 'country.LA',
  [CountryCode.LB]: 'country.LB',
  [CountryCode.LC]: 'country.LC',
  [CountryCode.LI]: 'country.LI',
  [CountryCode.LK]: 'country.LK',
  [CountryCode.LR]: 'country.LR',
  [CountryCode.LS]: 'country.LS',
  [CountryCode.LT]: 'country.LT',
  [CountryCode.LU]: 'country.LU',
  [CountryCode.LV]: 'country.LV',
  [CountryCode.LY]: 'country.LY',
  [CountryCode.MA]: 'country.MA',
  [CountryCode.MC]: 'country.MC',
  [CountryCode.MD]: 'country.MD',
  [CountryCode.ME]: 'country.ME',
  [CountryCode.MG]: 'country.MG',
  [CountryCode.MH]: 'country.MH',
  [CountryCode.MK]: 'country.MK',
  [CountryCode.ML]: 'country.ML',
  [CountryCode.MM]: 'country.MM',
  [CountryCode.MN]: 'country.MN',
  [CountryCode.MO]: 'country.MO',
  [CountryCode.MP]: 'country.MP',
  [CountryCode.MQ]: 'country.MQ',
  [CountryCode.MR]: 'country.MR',
  [CountryCode.MS]: 'country.MS',
  [CountryCode.MT]: 'country.MT',
  [CountryCode.MU]: 'country.MU',
  [CountryCode.MV]: 'country.MV',
  [CountryCode.MW]: 'country.MW',
  [CountryCode.MX]: 'country.MX',
  [CountryCode.MY]: 'country.MY',
  [CountryCode.MZ]: 'country.MZ',
  [CountryCode.NA]: 'country.NA',
  [CountryCode.NE]: 'country.NE',
  [CountryCode.NF]: 'country.NF',
  [CountryCode.NG]: 'country.NG',
  [CountryCode.NI]: 'country.NI',
  [CountryCode.NL]: 'country.NL',
  [CountryCode.NO]: 'country.NO',
  [CountryCode.NP]: 'country.NP',
  [CountryCode.NR]: 'country.NR',
  [CountryCode.NU]: 'country.NU',
  [CountryCode.NZ]: 'country.NZ',
  [CountryCode.OM]: 'country.OM',
  [CountryCode.PA]: 'country.PA',
  [CountryCode.PE]: 'country.PE',
  [CountryCode.PF]: 'country.PF',
  [CountryCode.PG]: 'country.PG',
  [CountryCode.PH]: 'country.PH',
  [CountryCode.PK]: 'country.PK',
  [CountryCode.PL]: 'country.PL',
  [CountryCode.PN]: 'country.PN',
  [CountryCode.PR]: 'country.PR',
  [CountryCode.PS]: 'country.PS',
  [CountryCode.PT]: 'country.PT',
  [CountryCode.PW]: 'country.PW',
  [CountryCode.PY]: 'country.PY',
  [CountryCode.QA]: 'country.QA',
  [CountryCode.RO]: 'country.RO',
  [CountryCode.RS]: 'country.RS',
  [CountryCode.RU]: 'country.RU',
  [CountryCode.RW]: 'country.RW',
  [CountryCode.SA]: 'country.SA',
  [CountryCode.SB]: 'country.SB',
  [CountryCode.SC]: 'country.SC',
  [CountryCode.SE]: 'country.SE',
  [CountryCode.SG]: 'country.SG',
  [CountryCode.SI]: 'country.SI',
  [CountryCode.SK]: 'country.SK',
  [CountryCode.SL]: 'country.SL',
  [CountryCode.SM]: 'country.SM',
  [CountryCode.SN]: 'country.SN',
  [CountryCode.SO]: 'country.SO',
  [CountryCode.SR]: 'country.SR',
  [CountryCode.SS]: 'country.SS',
  [CountryCode.ST]: 'country.ST',
  [CountryCode.SV]: 'country.SV',
  [CountryCode.SX]: 'country.SX',
  [CountryCode.SY]: 'country.SY',
  [CountryCode.SZ]: 'country.SZ',
  [CountryCode.TC]: 'country.TC',
  [CountryCode.TD]: 'country.TD',
  [CountryCode.TG]: 'country.TG',
  [CountryCode.TH]: 'country.TH',
  [CountryCode.TJ]: 'country.TJ',
  [CountryCode.TK]: 'country.TK',
  [CountryCode.TL]: 'country.TL',
  [CountryCode.TM]: 'country.TM',
  [CountryCode.TN]: 'country.TN',
  [CountryCode.TO]: 'country.TO',
  [CountryCode.TR]: 'country.TR',
  [CountryCode.TT]: 'country.TT',
  [CountryCode.TV]: 'country.TV',
  [CountryCode.TW]: 'country.TW',
  [CountryCode.TZ]: 'country.TZ',
  [CountryCode.UA]: 'country.UA',
  [CountryCode.UG]: 'country.UG',
  [CountryCode.US]: 'country.US',
  [CountryCode.UY]: 'country.UY',
  [CountryCode.UZ]: 'country.UZ',
  [CountryCode.VC]: 'country.VC',
  [CountryCode.VE]: 'country.VE',
  [CountryCode.VG]: 'country.VG',
  [CountryCode.VI]: 'country.VI',
  [CountryCode.VN]: 'country.VN',
  [CountryCode.VU]: 'country.VU',
  [CountryCode.WS]: 'country.WS',
  [CountryCode.YE]: 'country.YE',
  [CountryCode.ZA]: 'country.ZA',
  [CountryCode.ZM]: 'country.ZM',
  [CountryCode.ZW]: 'country.ZW',
  [CountryCode.AQ]: 'country.AQ',
  [CountryCode.BV]: 'country.BV',
  [CountryCode.CV]: 'country.CV',
  [CountryCode.CG]: 'country.CG',
  [CountryCode.CI]: 'country.CI',
  [CountryCode.GF]: 'country.GF',
  [CountryCode.TF]: 'country.TF',
  [CountryCode.GP]: 'country.GP',
  [CountryCode.HM]: 'country.HM',
  [CountryCode.VA]: 'country.VA',
  [CountryCode.YT]: 'country.YT',
  [CountryCode.AN]: 'country.AN',
  [CountryCode.NC]: 'country.NC',
  [CountryCode.RE]: 'country.RE',
  [CountryCode.SH]: 'country.SH',
  [CountryCode.PM]: 'country.PM',
  [CountryCode.GS]: 'country.GS',
  [CountryCode.SD]: 'country.SD',
  [CountryCode.SJ]: 'country.SJ',
  [CountryCode.UM]: 'country.UM',
};
