export enum Permission {
  // authen
  AUTH_CHANGE_PIN = 'AUTH_CHANGE_PIN',
  AUTH_CHANGE_MAIL = 'AUTH_CHANGE_MAIL',
  AUTH_CHANGE_WALLET = 'AUTH_CHANGE_WALLET',
  AUTH_MAIL_CHANGE_WALLET = 'AUTH_MAIL_CHANGE_WALLET',

  // user
  USER_GET_INFO = 'USER_GET_INFO',
  USER_CHANGE_INFO = 'USER_CHANGE_INFO',
  USER_APPLY_LEADER = 'USER_APPLY_LEADER',
  USER_APPLY_EXPERT = 'USER_APPLY_EXPERT',
  USER_CANCEL_LEADER = 'USER_CANCEL_LEADER',
  USER_CANCEL_EXPERT = 'USER_CANCEL_EXPERT',
  USER_GET_INFO_OTHER_USER = 'USER_GET_INFO_OTHER_USER',
  USER_GET_LIST_LEADER_INVESTOR_CHILDREN = 'USER_GET_LIST_LEADER_INVESTOR_CHILDREN',

  // tài sản user
  USER_WALLET_GET_INFO = 'USER_WALLET_GET_INFO',

  // giao dịch
  // mua
  TRANSACTION_BUY = 'TRANSACTION_BUY',
  TRANSACTION_WITHDRAW = 'TRANSACTION_WITHDRAW',
  TRANSACTION_TRANSFER = 'TRANSACTION_TRANSFER',

  // thưởng
  TRANSACTION_BONUS_WITHDRAW = 'TRANSACTION_BONUS_WITHDRAW',

  // danh sách giao dịch
  TRANSACTION_GET_LIST = 'TRANSACTION_GET_LIST',

  // kỳ
  PERIOD_GET_CURRENT = 'PERIOD_GET_CURRENT',

  // blog
  ARTICLE_GET_LIST = 'ARTICLE_GET_LIST',
  ARTICLE_GET_DETAIL = 'ARTICLE_GET_DETAIL',
  ARTICLE_CREATE_DRAFT = 'ARTICLE_CREATE_DRAFT',
  ARTICLE_SEND_FOR_APPROVING = 'ARTICLE_SEND_FOR_APPROVING',
  ARTICLE_UPDATE = 'ARTICLE_UPDATE',
  ARTICLE_DELETE = 'ARTICLE_DELETE',
  ARTICLE_APPROVE = 'ARTICLE_APPROVE',
  ARTICLE_DISAPPROVE = 'ARTICLE_DISAPPROVE',
  ARTICLE_RETRIEVE = 'ARTICLE_RETRIEVE',
}

// export const permissionsArray: Permission[] = [Permission.ROLE_ADMIN];

export const investorPermArr: Permission[] = [
  Permission.USER_APPLY_LEADER,
  Permission.USER_GET_INFO_OTHER_USER,
  Permission.USER_WALLET_GET_INFO,
  Permission.TRANSACTION_BUY,
  Permission.TRANSACTION_WITHDRAW,
  Permission.TRANSACTION_TRANSFER,
  Permission.TRANSACTION_BONUS_WITHDRAW,
  Permission.TRANSACTION_GET_LIST,
  Permission.PERIOD_GET_CURRENT,
];

export const leaderPermArr: Permission[] = [
  Permission.USER_APPLY_EXPERT,
  Permission.USER_CANCEL_LEADER,
  Permission.USER_CANCEL_EXPERT,
  Permission.USER_GET_LIST_LEADER_INVESTOR_CHILDREN,
];

export const expertPermArr: Permission[] = [
  Permission.ARTICLE_GET_LIST,
  Permission.ARTICLE_GET_DETAIL,
  Permission.ARTICLE_CREATE_DRAFT,
  Permission.ARTICLE_SEND_FOR_APPROVING,
  Permission.ARTICLE_UPDATE,
  Permission.ARTICLE_DELETE,
  Permission.ARTICLE_APPROVE,
  Permission.ARTICLE_DISAPPROVE,
  Permission.ARTICLE_RETRIEVE,
];
